### ISSUE TITLE
Drop-Delay popup requires scrolling

### ISSUE THREAD

**Issue by cohoe** [ComputerScienceHouse/Drink-JS#13]
If I scroll down on the main page, drop a snack, I have to scroll all the way back up to see the drop-delay popup. Would be nice if this displayed at the middle of the page regardless of scrolling location.

**Comment by clockfort** [comment]
Workaround: Buy Cohoe a higher-resolution monitor.

**Comment by cohoe** [comment]
I only accept monitors in groups of three. 3 30" panels should do it.

**Comment by clockfort** [comment]
Alright, we'll send McGary the bill.

**Comment by seanmcgary** [comment]
Problem fixed. Popup will now appear where your screen is scrolled to.
