### ISSUE TITLE
Not rendering machines or drops.

### ISSUE THREAD

**Issue by sgg** [ComputerScienceHouse/Drink-JS#15]
If you hit either the 'Machines' or 'Your Drops' button you recieve this error:

"event.layerX and event.layerY are broken and deprecated in WebKit. They will be removed from the engine in the near future."

**Comment by seanmcgary** [comment]
This isnt actually an error, warning from jQuery, and shouldnt affect JS execution. Looks like they are already on it and will have it fixed in the next jQuery release (http://bugs.jquery.com/ticket/10531)
