### ISSUE TITLE
Snack Counts

### ISSUE THREAD

**Issue by crawford** [ComputerScienceHouse/Drink-JS#16]
The counts for snack remain at 1 even when the slot is empty. Yes this is a hardware bug, but you'll have to work around it. We need a way to override the slot empty status returned from hardware.

**Comment by danw** [comment]
In the old server, we supported a per-machine setting on whether the machine has a empty sensor or not. Machines without empty sensors should return 1...

**Comment by seanmcgary** [comment]
Added a flag to the machine config denoting if the machine has a sensor or not. This is then checked before updating slot statuses based on the sensor data.
