### ISSUE TITLE
running node/drink server as root user

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/Drink-JS#18]
r u srs

**Comment by ewenig** [comment]
Wait, really?

**Comment by mveety** [comment]
Is there any legitimate reason it should be?

**Comment by clockfort** [comment]
Clearly no reason why it should be. At worst if he needs a low port he
should grab it and drop privs, obviously.

On Nov 3, 2011, at 10:42, Matthew Veety
reply@reply.github.com
wrote:

**Comment by seanmcgary** [comment]
Yeah this was a small fuckup on my part when I restarted the server yesterday. The server should be run (and is now running) under the drink user.
