### ISSUE TITLE
drink dropping broken in mobile opera

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/Drink-JS#20]
used to work previously (even with drink-js), and somehow no longer does. 

Dropping interface now both renders incorrectly /and/ doesn't actually function.

Screenshot: http://csh.rit.edu/~clockfort/images/drinkjs_opera_mobile_screenshot.png

**Comment by seanmcgary** [comment]
Ive also been seeing this problem in mobile safari on iOS5. The only difference is that it renders properly at first, but after dropping, it doesnt remove the modal and overlay. Im guessing its websocket related and not receiving the drop ack. Looking into fixing it.

**Comment by seanmcgary** [comment]
Moving to WebDrink issues - https://github.com/ComputerScienceHouse/WebDrink/issues/3
