### ISSUE TITLE
Adding items does not check for unique constraints

### ISSUE THREAD

**Issue by clockfort** [ComputerScienceHouse/Drink-JS#26]
i.e. if I add "JOLT Grape" and click the add button multiple times (which people will click a million times since there is absolutely zero indication to the user that the action has completed, since the text fields are not cleared) multiple items are added to the database

**Comment by seanmcgary** [comment]
Moving to WebDrink issues - https://github.com/ComputerScienceHouse/WebDrink/issues/2
