### ISSUE TITLE
logger.js Error

### ISSUE THREAD

**Issue by cohoe** [ComputerScienceHouse/Drink-JS#31]
logger.js: 19 Uncaught ReferenceError: io is not defined.

var log_socket = io.connect('https://drink.csh.rit.edu:8081');

I get this in both Chrome and FF. 

WebDrink shows "CSH Drink", "Hello $me ($credits)", "Machines", "Your Drops", and that's it.

**Comment by seanmcgary** [comment]
If you open up the chrome inspector, check that the socket.io JavaScript file is loading. If its not, that's why. I'm working on fixing this bug.
