### ISSUE TITLE
Limit the max amount of time for drops

### ISSUE THREAD

**Issue by seanmcgary** [ComputerScienceHouse/Drink-JS#44]
Slackwill is an asshat and dropped a drink with a HUUUUGE delay. So we're gonna set an upper limit to that....

**Comment by brysgo** [comment]
Why don't you just change it so that the system doesn't block during a delay?

**Comment by seanmcgary** [comment]
Thats exactly what Im working on :)

**Comment by seanmcgary** [comment]
Fixed in efb75461ad4973d1e2119c59f5ec47c4c2070d64
